version: '2'

networks:

services:
  backend_dev:
    container_name: habee_backend_dev
    build: ./backend/
    environment:
      - VIRTUAL_HOST=si.habee.local
    volumes : 
      - ./backend/:/usr/src/app:rw
    ports:
      - "80:3000"
    links:
      - mongo
  
  mongo:
    container_name: habee_mongo_dev
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"