version: '2'

services:

  version: '2'

networks:
  mongodb_net:
    driver: bridge
    ipam:
      driver: default
      config:
      # Change this subnet range if it conflicts with your personal/work network
        - subnet: 192.168.213.0/24
          gateway: 192.168.213.1  

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    container_name: habee_nginx

  backend_dev:
    container_name: habee_backend_dev
    build: ./backend/
    environment:
      - VIRTUAL_HOST=si.habee.local
    volumes : 
      - ./backend/:/usr/src/app:rw
    ports:
      - "3000:3000"
    links:
      - mongo
  
  mongo:
    container_name: habee_mongo_dev
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  frontend_dev:
    container_name: habee_frontend_dev
    build: frontend/
    volumes :
      - ./frontend/:/usr/src/app:rw
    environment:
      - VIRTUAL_HOST=app.habee.local
    ports:
      - "8100:8100"
      
  
  mongoclient:
    image: mongoclient/mongoclient:latest
    container_name: mongoclient
    hostname: mongoclient
    environment:
      - VIRTUAL_HOST=app.habeedb.local
    depends_on:
      - mongo
    networks:
      - mongodb_net
    ports:
      - 3300:3000
